// =====================================================================
//  BANQUE D'EXERCICES EN PORTUGAIS (v6.19) — même structure que exercises-en.js
// =====================================================================
window.BANK_PT = {
  denomination:{ title:'Nomear as imagens', items:{
    1:[ {emoji:'🐱',answer:'GATO',choices:['GATO','CÃO','COELHO']},
        {emoji:'🍎',answer:'MAÇÃ',choices:['PERA','MAÇÃ','AMEIXA']},
        {emoji:'🏠',answer:'CASA',choices:['CASA','CARRO','ÁRVORE']},
        {emoji:'☀️',answer:'SOL',choices:['SOL','LUA','NUVEM']},
        {emoji:'🚗',answer:'CARRO',choices:['CARRO','BICICLETA','BARCO']},
        {emoji:'🐟',answer:'PEIXE',choices:['PEIXE','PÁSSARO','CAVALO']},
        {emoji:'🌹',answer:'FLOR',choices:['FLOR','RELVA','FOLHA']},
        {emoji:'🍞',answer:'PÃO',choices:['PÃO','BOLO','QUEIJO']} ],
    2:[ {emoji:'🦋',answer:'BORBOLETA',choices:['BORBOLETA','ABELHA','LIBÉLULA']},
        {emoji:'⌚',answer:'RELÓGIO',choices:['RELÓGIO','LIVRO','CANDEEIRO']},
        {emoji:'🎻',answer:'VIOLINO',choices:['GUITARRA','VIOLINO','VIOLONCELO']},
        {emoji:'🍄',answer:'COGUMELO',choices:['COGUMELO','TOMATE','CEBOLA']},
        {emoji:'🦒',answer:'GIRAFA',choices:['GIRAFA','CAMELO','ZEBRA']},
        {emoji:'⛵',answer:'VELEIRO',choices:['VELEIRO','NAVIO','CANOA']},
        {emoji:'🎺',answer:'TROMPETE',choices:['TROMPETE','FLAUTA','SAXOFONE']},
        {emoji:'🌋',answer:'VULCÃO',choices:['VULCÃO','MONTANHA','COLINA']} ],
    3:[ {emoji:'🧭',answer:'BÚSSOLA',choices:['BÚSSOLA','BARÓMETRO','TERMÓMETRO']},
        {emoji:'🦔',answer:'OURIÇO',choices:['OURIÇO','PORCO-ESPINHO','TOUPEIRA']},
        {emoji:'⚓',answer:'ÂNCORA',choices:['ÂNCORA','HÉLICE','LEME']},
        {emoji:'🔬',answer:'MICROSCÓPIO',choices:['MICROSCÓPIO','TELESCÓPIO','ESTETOSCÓPIO']},
        {emoji:'🪕',answer:'BANJO',choices:['BANJO','BANDOLIM','UKULELE']},
        {emoji:'🦦',answer:'LONTRA',choices:['LONTRA','DONINHA','MARTA']},
        {emoji:'🌪️',answer:'TORNADO',choices:['TORNADO','FURACÃO','TUFÃO']},
        {emoji:'🛡️',answer:'ESCUDO',choices:['ESCUDO','ARMADURA','CAPACETE']} ]
  }},
  completion:{ title:'Completar a frase', items:{
    1:[ {text:'O gato bebe ___',answer:'LEITE',choices:['LEITE','PÃO','ÁGUA']},
        {text:'Durmo na minha ___',answer:'CAMA',choices:['CAMA','CADEIRA','PORTA']},
        {text:'O sol é ___',answer:'AMARELO',choices:['AMARELO','FRIO','PESADO']},
        {text:'Como com um ___',answer:'GARFO',choices:['GARFO','CADEIRA','PORTA']},
        {text:'À noite, o céu é ___',answer:'PRETO',choices:['PRETO','VERDE','REDONDO']},
        {text:'Ando com os meus ___',answer:'PÉS',choices:['PÉS','MÃOS','OLHOS']},
        {text:'Bebemos de um ___',answer:'COPO',choices:['COPO','LIVRO','MURO']},
        {text:'O bebé chora no ___',answer:'BERÇO',choices:['BERÇO','JARDIM','FORNO']} ],
    2:[ {text:'Para escrever, uso uma ___',answer:'CANETA',choices:['CANETA','MARTELO','VASSOURA']},
        {text:'No inverno, faz muito ___',answer:'FRIO',choices:['CALOR','FRIO','HÚMIDO']},
        {text:'O carteiro traz o ___',answer:'CORREIO',choices:['CORREIO','PÃO','JORNAL']},
        {text:'Para abrir a porta, preciso de uma ___',answer:'CHAVE',choices:['CHAVE','CANDEEIRO','CHÁVENA']},
        {text:'Vejo um filme na ___',answer:'TELEVISÃO',choices:['TELEVISÃO','RÁDIO','JANELA']},
        {text:'O pássaro constrói o seu ___',answer:'NINHO',choices:['NINHO','BURACO','MURO']},
        {text:'Compramos pão na ___',answer:'PADARIA',choices:['PADARIA','FARMÁCIA','BANCO']},
        {text:'Antes de comer, lavo as ___',answer:'MÃOS',choices:['MÃOS','CABELO','DENTES']} ],
    3:[ {text:'Antes de sair, não te esqueças de ___ a porta',answer:'FECHAR',choices:['FECHAR','ABRIR','PINTAR']},
        {text:'O médico receitou um ___',answer:'TRATAMENTO',choices:['TRATAMENTO','DOCE','RAMO']},
        {text:'A reunião foi ___ para amanhã',answer:'ADIADA',choices:['ADIADA','COMIDA','PINTADA']},
        {text:'Tens de ___ os teus impostos antes do prazo',answer:'DECLARAR',choices:['DECLARAR','DANÇAR','REGAR']},
        {text:'O jardineiro vai ___ as roseiras',answer:'PODAR',choices:['PODAR','LER','NADAR']},
        {text:'Depois do exercício, é preciso ___',answer:'DESCANSAR',choices:['DESCANSAR','CORRER','ZANGAR-SE']},
        {text:'Esta história é difícil de ___',answer:'ACREDITAR',choices:['ACREDITAR','COSER','CORTAR']},
        {text:'A testemunha recusou-se a ___',answer:'TESTEMUNHAR',choices:['TESTEMUNHAR','LIGAR','VIAJAR']} ]
  }},
  comprehension:{ title:'Compreender a instrução', items:{
    1:[ {text:'Que animal ladra?',answer:'O CÃO',choices:['O CÃO','O PEIXE','O PÁSSARO']},
        {text:'Com que se come a sopa?',answer:'UMA COLHER',choices:['UMA COLHER','UMA FACA','UM GARFO']},
        {text:'Onde se dorme?',answer:'NUMA CAMA',choices:['NUMA CAMA','NUMA TIGELA','NUM SACO']},
        {text:'De que cor é a relva?',answer:'VERDE',choices:['VERDE','VERMELHA','AZUL']},
        {text:'O que se bebe quando se tem sede?',answer:'ÁGUA',choices:['ÁGUA','AREIA','PAPEL']},
        {text:'Que objeto ilumina a noite?',answer:'UM CANDEEIRO',choices:['UM CANDEEIRO','UMA ALMOFADA','UM PRATO']} ],
    2:[ {text:'Que objeto indica as horas?',answer:'UM RELÓGIO',choices:['UM RELÓGIO','UM LIVRO','UM CANDEEIRO']},
        {text:'Que estação vem depois do inverno?',answer:'A PRIMAVERA',choices:['O VERÃO','A PRIMAVERA','O OUTONO']},
        {text:'Para que serve um guarda-chuva?',answer:'PARA NÃO MOLHAR',choices:['PARA NÃO MOLHAR','PARA COMER','PARA DORMIR']},
        {text:'Que profissão trata os doentes?',answer:'O MÉDICO',choices:['O MÉDICO','O PADEIRO','O PINTOR']},
        {text:'Quantos dias tem uma semana?',answer:'SETE',choices:['SETE','CINCO','DEZ']},
        {text:'Onde se compram medicamentos?',answer:'NA FARMÁCIA',choices:['NA FARMÁCIA','NOS CORREIOS','NA OFICINA']} ],
    3:[ {text:'Se todas as rosas são flores, uma rosa é uma flor?',answer:'SIM',choices:['SIM','NÃO','ÀS VEZES','NÃO SE SABE']},
        {text:'O contrário de "rapidamente" é:',answer:'LENTAMENTE',choices:['LENTAMENTE','FORTEMENTE','ALEGREMENTE']},
        {text:'"Chove a cântaros" significa:',answer:'CHOVE MUITO',choices:['CHOVE MUITO','ESTÁ SOL','ESTÁ VENTO']},
        {text:'O Pedro é mais alto que o Paulo. Quem é mais baixo?',answer:'PAULO',choices:['PAULO','PEDRO','OS DOIS','NENHUM']},
        {text:'"Virar a página" significa:',answer:'SEGUIR EM FRENTE',choices:['SEGUIR EM FRENTE','LER UM LIVRO','DESCANSAR']},
        {text:'Que palavra não é uma fruta?',answer:'CENOURA',choices:['CENOURA','CEREJA','BANANA']} ]
  }},
  repetition:{ title:'Repetir em voz alta', voice:true, items:{
    1:[ {word:'BOLA'},{word:'MESA'},{word:'SOL'},{word:'GATO'},{word:'PORTA'},{word:'FLOR'},{word:'MÃO'},{word:'ÁGUA'} ],
    2:[ {word:'COMPUTADOR'},{word:'GUARDA-CHUVA'},{word:'TELEFONE'},{word:'BIBLIOTECA'},{word:'RESTAURANTE'},{word:'MONTANHA'},{word:'JARDINEIRO'},{word:'CALENDÁRIO'} ],
    3:[ {word:'HELICÓPTERO'},{word:'FISIOTERAPEUTA'},{word:'INCONSTITUCIONAL'},{word:'PARALELEPÍPEDO'},{word:'OTORRINOLARINGOLOGISTA'},{word:'CRISÂNTEMO'},{word:'PROXIMAMENTE'},{word:'ESTATISTICAMENTE'} ]
  }},
  denomination_orale:{ title:'Nomear em voz alta', voice:true, items:{
    1:[ {emoji:'🐱',word:'GATO'},{emoji:'🍎',word:'MAÇÃ'},{emoji:'🏠',word:'CASA'},{emoji:'☀️',word:'SOL'},{emoji:'🚗',word:'CARRO'},{emoji:'🌹',word:'FLOR'} ],
    2:[ {emoji:'🦋',word:'BORBOLETA'},{emoji:'⌚',word:'RELÓGIO'},{emoji:'🍄',word:'COGUMELO'},{emoji:'🦒',word:'GIRAFA'},{emoji:'⛵',word:'VELEIRO'},{emoji:'🎺',word:'TROMPETE'} ],
    3:[ {emoji:'🧭',word:'BÚSSOLA'},{emoji:'🦔',word:'OURIÇO'},{emoji:'⚓',word:'ÂNCORA'},{emoji:'🔬',word:'MICROSCÓPIO'},{emoji:'🌪️',word:'TORNADO'},{emoji:'🛡️',word:'ESCUDO'} ]
  }},
  fluence:{ title:'Fluência verbal', voice:true, fluency:true, items:{
    1:[ {cat:'animais',accept:['gato','cão','coelho','cavalo','vaca','galinha','ovelha','porco','pássaro','peixe','rato','leão','tigre','urso','lobo','raposa','pato','burro','cabra','macaco','elefante','girafa','zebra','cobra','rã']},
        {cat:'frutas',accept:['maçã','pera','banana','laranja','morango','cereja','uva','kiwi','melão','pêssego','alperce','ameixa','limão','ananás','manga','framboesa','mirtilo','melancia','figo','tangerina']} ],
    2:[ {cat:'objetos de cozinha',accept:['faca','garfo','colher','prato','copo','panela','frigideira','forno','frigorífico','lava-loiça','mesa','chávena','tigela','coador','espátula','concha','travessa','chaleira','bule']},
        {cat:'roupa',accept:['calças','camisa','camisola','vestido','saia','casaco','blusão','meia','sapato','cachecol','luva','chapéu','calções','t-shirt','gravata','cinto','bota','sandália','collants','casaco de malha']} ],
    3:[ {cat:'palavras que começam pela letra B',accept:['barco','bola','pão','livro','bota','pássaro','cama','garrafa','banana','sino','saco','praia','escova','botão','urso','ramo','ponte','cesto','manta','manteiga']},
        {cat:'profissões',accept:['médico','padeiro','bombeiro','professor','enfermeira','advogado','canalizador','pintor','cozinheiro','carteiro','jardineiro','cabeleireiro','mecânico','farmacêutico','eletricista','arquiteto','jornalista','polícia','piloto','dentista']} ]
  }},
  intonation:{ title:'Repetir com entoação', voice:true, items:{
    1:[ {word:'Já acabaste?',cue:'question'},
        {word:'Tens a certeza?',cue:'question'},
        {word:'Venho amanhã.',cue:'descriptive'},
        {word:'Comes aqui.',cue:'descriptive'},
        {word:'Vem aqui!',cue:'exclamative'},
        {word:'Que boa ideia!',cue:'exclamative'} ],
    2:[ {word:'O que estás a fazer?',cue:'question'},
        {word:'A sério?',cue:'question'},
        {word:'Ela brinca lá fora.',cue:'descriptive'},
        {word:'Estão a falar com um amigo.',cue:'descriptive'},
        {word:'Como estás bonit·o!',cue:'exclamative'},
        {word:'Que surpresa!',cue:'exclamative'} ],
    3:[ {word:'Dormiste bem esta noite?',cue:'question'},
        {word:'Podias ajudar-me a levar isto?',cue:'question'},
        {word:'Vamos sair cedo amanhã de manhã.',cue:'descriptive'},
        {word:'O carteiro veio enquanto dormias.',cue:'descriptive'},
        {word:'Que dia maravilhoso tivemos!',cue:'exclamative'},
        {word:'Ainda não acredito!',cue:'exclamative'} ]
  }}
};
