// =====================================================================
//  BANQUE D'EXERCICES EN ITALIEN (v6.19) — même structure que exercises-en.js
// =====================================================================
window.BANK_IT = {
  denomination:{ title:'Nominare le immagini', items:{
    1:[ {emoji:'🐱',answer:'GATTO',choices:['GATTO','CANE','CONIGLIO']},
        {emoji:'🍎',answer:'MELA',choices:['PERA','MELA','SUSINA']},
        {emoji:'🏠',answer:'CASA',choices:['CASA','AUTO','ALBERO']},
        {emoji:'☀️',answer:'SOLE',choices:['SOLE','LUNA','NUVOLA']},
        {emoji:'🚗',answer:'AUTO',choices:['AUTO','BICI','BARCA']},
        {emoji:'🐟',answer:'PESCE',choices:['PESCE','UCCELLO','CAVALLO']},
        {emoji:'🌹',answer:'FIORE',choices:['FIORE','ERBA','FOGLIA']},
        {emoji:'🍞',answer:'PANE',choices:['PANE','TORTA','FORMAGGIO']} ],
    2:[ {emoji:'🦋',answer:'FARFALLA',choices:['FARFALLA','APE','LIBELLULA']},
        {emoji:'⌚',answer:'OROLOGIO',choices:['OROLOGIO','LIBRO','LAMPADA']},
        {emoji:'🎻',answer:'VIOLINO',choices:['CHITARRA','VIOLINO','VIOLONCELLO']},
        {emoji:'🍄',answer:'FUNGO',choices:['FUNGO','POMODORO','CIPOLLA']},
        {emoji:'🦒',answer:'GIRAFFA',choices:['GIRAFFA','CAMMELLO','ZEBRA']},
        {emoji:'⛵',answer:'BARCA A VELA',choices:['BARCA A VELA','NAVE','CANOA']},
        {emoji:'🎺',answer:'TROMBA',choices:['TROMBA','FLAUTO','SASSOFONO']},
        {emoji:'🌋',answer:'VULCANO',choices:['VULCANO','MONTAGNA','COLLINA']} ],
    3:[ {emoji:'🧭',answer:'BUSSOLA',choices:['BUSSOLA','BAROMETRO','TERMOMETRO']},
        {emoji:'🦔',answer:'RICCIO',choices:['RICCIO','ISTRICE','TALPA']},
        {emoji:'⚓',answer:'ANCORA',choices:['ANCORA','ELICA','TIMONE']},
        {emoji:'🔬',answer:'MICROSCOPIO',choices:['MICROSCOPIO','TELESCOPIO','STETOSCOPIO']},
        {emoji:'🪕',answer:'BANJO',choices:['BANJO','MANDOLINO','UKULELE']},
        {emoji:'🦦',answer:'LONTRA',choices:['LONTRA','DONNOLA','MARTORA']},
        {emoji:'🌪️',answer:'TORNADO',choices:['TORNADO','URAGANO','TIFONE']},
        {emoji:'🛡️',answer:'SCUDO',choices:['SCUDO','ARMATURA','ELMO']} ]
  }},
  completion:{ title:'Completare la frase', items:{
    1:[ {text:'Il gatto beve ___',answer:'LATTE',choices:['LATTE','PANE','ACQUA']},
        {text:'Dormo nel mio ___',answer:'LETTO',choices:['LETTO','PIATTO','SACCO']},
        {text:'Il sole è ___',answer:'GIALLO',choices:['GIALLO','FREDDO','PESANTE']},
        {text:'Mangio con una ___',answer:'FORCHETTA',choices:['FORCHETTA','SEDIA','PORTA']},
        {text:'Di notte, il cielo è ___',answer:'NERO',choices:['NERO','VERDE','ROTONDO']},
        {text:'Cammino con i miei ___',answer:'PIEDI',choices:['PIEDI','MANI','OCCHI']},
        {text:'Beviamo da un ___',answer:'BICCHIERE',choices:['BICCHIERE','LIBRO','MURO']},
        {text:'Il bambino piange nella ___',answer:'CULLA',choices:['CULLA','GIARDINO','FORNO']} ],
    2:[ {text:'Per scrivere, uso una ___',answer:'PENNA',choices:['PENNA','MARTELLO','SCOPA']},
        {text:"D'inverno fa molto ___",answer:'FREDDO',choices:['CALDO','FREDDO','UMIDO']},
        {text:'Il postino porta la ___',answer:'POSTA',choices:['POSTA','PANE','GIORNALE']},
        {text:'Per aprire la porta serve una ___',answer:'CHIAVE',choices:['CHIAVE','LAMPADA','TAZZA']},
        {text:'Guardo un film alla ___',answer:'TELEVISIONE',choices:['TELEVISIONE','RADIO','FINESTRA']},
        {text:'L\'uccello costruisce il suo ___',answer:'NIDO',choices:['NIDO','BUCO','MURO']},
        {text:'Compriamo il pane in ___',answer:'PANETTERIA',choices:['PANETTERIA','FARMACIA','BANCA']},
        {text:'Prima di mangiare, mi lavo le ___',answer:'MANI',choices:['MANI','CAPELLI','DENTI']} ],
    3:[ {text:'Prima di uscire, non dimenticare di ___ la porta',answer:'CHIUDERE',choices:['CHIUDERE','APRIRE','DIPINGERE']},
        {text:'Il medico ha prescritto una ___',answer:'CURA',choices:['CURA','DESSERT','MAZZO DI FIORI']},
        {text:'La riunione è stata ___ a domani',answer:'RINVIATA',choices:['RINVIATA','MANGIATA','DIPINTA']},
        {text:'Devi ___ le tasse entro la scadenza',answer:'DICHIARARE',choices:['DICHIARARE','BALLARE','ANNAFFIARE']},
        {text:'Il giardiniere sta per ___ i rosai',answer:'POTARE',choices:['POTARE','LEGGERE','NUOTARE']},
        {text:'Dopo lo sport, bisogna ___',answer:'RIPOSARE',choices:['RIPOSARE','CORRERE','ARRABBIARSI']},
        {text:'Questa storia è difficile da ___',answer:'CREDERE',choices:['CREDERE','CUCIRE','TAGLIARE']},
        {text:'Il testimone ha rifiutato di ___',answer:'TESTIMONIARE',choices:['TESTIMONIARE','CHIAMARE','VIAGGIARE']} ]
  }},
  comprehension:{ title:'Capire la consegna', items:{
    1:[ {text:'Quale animale abbaia?',answer:'IL CANE',choices:['IL CANE','IL PESCE','L\'UCCELLO']},
        {text:'Con cosa si mangia la zuppa?',answer:'UN CUCCHIAIO',choices:['UN CUCCHIAIO','UN COLTELLO','UNA FORCHETTA']},
        {text:'Dove si dorme?',answer:'IN UN LETTO',choices:['IN UN LETTO','IN UNA CIOTOLA','IN UNA BORSA']},
        {text:'Di che colore è l\'erba?',answer:'VERDE',choices:['VERDE','ROSSA','BLU']},
        {text:'Cosa si beve quando si ha sete?',answer:'ACQUA',choices:['ACQUA','SABBIA','CARTA']},
        {text:'Quale oggetto illumina la notte?',answer:'UNA LAMPADA',choices:['UNA LAMPADA','UN CUSCINO','UN PIATTO']} ],
    2:[ {text:'Quale oggetto indica l\'ora?',answer:'UN OROLOGIO',choices:['UN OROLOGIO','UN LIBRO','UNA LAMPADA']},
        {text:'Quale stagione viene dopo l\'inverno?',answer:'LA PRIMAVERA',choices:['L\'ESTATE','LA PRIMAVERA','L\'AUTUNNO']},
        {text:'A cosa serve un ombrello?',answer:'A NON BAGNARSI',choices:['A NON BAGNARSI','A MANGIARE','A DORMIRE']},
        {text:'Quale professione cura i malati?',answer:'IL MEDICO',choices:['IL MEDICO','IL FORNAIO','IL PITTORE']},
        {text:'Quanti giorni ci sono in una settimana?',answer:'SETTE',choices:['SETTE','CINQUE','DIECI']},
        {text:'Dove si comprano le medicine?',answer:'IN FARMACIA',choices:['IN FARMACIA','ALLA POSTA','IN OFFICINA']} ],
    3:[ {text:'Se tutte le rose sono fiori, una rosa è un fiore?',answer:'SÌ',choices:['SÌ','NO','A VOLTE','NON SI SA']},
        {text:'Il contrario di "velocemente" è:',answer:'LENTAMENTE',choices:['LENTAMENTE','FORTEMENTE','ALLEGRAMENTE']},
        {text:'"Piove a catinelle" significa:',answer:'PIOVE MOLTO',choices:['PIOVE MOLTO','C\'È IL SOLE','TIRA VENTO']},
        {text:'Pietro è più alto di Paolo. Chi è più basso?',answer:'PAOLO',choices:['PAOLO','PIETRO','ENTRAMBI','NESSUNO']},
        {text:'"Voltare pagina" significa:',answer:'ANDARE AVANTI',choices:['ANDARE AVANTI','LEGGERE UN LIBRO','RIPOSARE']},
        {text:'Quale parola non è un frutto?',answer:'CAROTA',choices:['CAROTA','CILIEGIA','BANANA']} ]
  }},
  repetition:{ title:'Ripetere ad alta voce', voice:true, items:{
    1:[ {word:'PALLA'},{word:'TAVOLO'},{word:'SOLE'},{word:'GATTO'},{word:'PORTA'},{word:'FIORE'},{word:'MANO'},{word:'ACQUA'} ],
    2:[ {word:'COMPUTER'},{word:'OMBRELLO'},{word:'TELEFONO'},{word:'BIBLIOTECA'},{word:'RISTORANTE'},{word:'MONTAGNA'},{word:'GIARDINIERE'},{word:'CALENDARIO'} ],
    3:[ {word:'ELICOTTERO'},{word:'FISIOTERAPISTA'},{word:'INCOSTITUZIONALE'},{word:'PARALLELEPIPEDO'},{word:'OTORINOLARINGOIATRA'},{word:'CRISANTEMO'},{word:'PROSSIMAMENTE'},{word:'STATISTICAMENTE'} ]
  }},
  denomination_orale:{ title:'Nominare ad alta voce', voice:true, items:{
    1:[ {emoji:'🐱',word:'GATTO'},{emoji:'🍎',word:'MELA'},{emoji:'🏠',word:'CASA'},{emoji:'☀️',word:'SOLE'},{emoji:'🚗',word:'AUTO'},{emoji:'🌹',word:'FIORE'} ],
    2:[ {emoji:'🦋',word:'FARFALLA'},{emoji:'⌚',word:'OROLOGIO'},{emoji:'🍄',word:'FUNGO'},{emoji:'🦒',word:'GIRAFFA'},{emoji:'⛵',word:'BARCA A VELA'},{emoji:'🎺',word:'TROMBA'} ],
    3:[ {emoji:'🧭',word:'BUSSOLA'},{emoji:'🦔',word:'RICCIO'},{emoji:'⚓',word:'ANCORA'},{emoji:'🔬',word:'MICROSCOPIO'},{emoji:'🌪️',word:'TORNADO'},{emoji:'🛡️',word:'SCUDO'} ]
  }},
  fluence:{ title:'Fluenza verbale', voice:true, fluency:true, items:{
    1:[ {cat:'animali',accept:['gatto','cane','coniglio','cavallo','mucca','gallina','pecora','maiale','uccello','pesce','topo','leone','tigre','orso','lupo','volpe','anatra','asino','capra','scimmia','elefante','giraffa','zebra','serpente','rana']},
        {cat:'frutta',accept:['mela','pera','banana','arancia','fragola','ciliegia','uva','kiwi','melone','pesca','albicocca','susina','limone','ananas','mango','lampone','mirtillo','anguria','fico','mandarino']} ],
    2:[ {cat:'oggetti da cucina',accept:['coltello','forchetta','cucchiaio','piatto','bicchiere','pentola','padella','forno','frigorifero','lavandino','tavolo','tazza','ciotola','colino','spatola','mestolo','vassoio','bollitore','teiera']},
        {cat:'vestiti',accept:['pantaloni','camicia','maglione','vestito','gonna','cappotto','giacca','calzino','scarpa','sciarpa','guanto','cappello','pantaloncini','maglietta','cravatta','cintura','stivale','sandalo','collant','cardigan']} ],
    3:[ {cat:'parole che iniziano con la lettera B',accept:['barca','palla','pane','libro','stivale','uccello','letto','bottiglia','banana','campana','borsa','spiaggia','spazzola','bottone','orso','ramo','ponte','cesto','coperta','burro']},
        {cat:'professioni',accept:['medico','fornaio','pompiere','insegnante','infermiera','avvocato','idraulico','pittore','cuoco','postino','giardiniere','parrucchiere','meccanico','farmacista','elettricista','architetto','giornalista','poliziotto','pilota','dentista']} ]
  }},
  intonation:{ title:"Ripetere con l'intonazione", voice:true, items:{
    1:[ {word:'Hai finito?',cue:'question'},
        {word:'Sei sicur·o?',cue:'question'},
        {word:'Arrivo domani.',cue:'descriptive'},
        {word:'Mangi qui.',cue:'descriptive'},
        {word:'Vieni qui!',cue:'exclamative'},
        {word:'Che buona idea!',cue:'exclamative'} ],
    2:[ {word:'Cosa stai facendo?',cue:'question'},
        {word:'Ah, davvero?',cue:'question'},
        {word:'Lei gioca fuori.',cue:'descriptive'},
        {word:'Parlano con un amico.',cue:'descriptive'},
        {word:'Come sei bell·o!',cue:'exclamative'},
        {word:'Che sorpresa!',cue:'exclamative'} ],
    3:[ {word:'Hai dormito bene stanotte?',cue:'question'},
        {word:'Potresti aiutarmi a portare questo?',cue:'question'},
        {word:'Partiremo presto domani mattina.',cue:'descriptive'},
        {word:'Il postino è venuto mentre dormivi.',cue:'descriptive'},
        {word:'Che giornata meravigliosa abbiamo avuto!',cue:'exclamative'},
        {word:'Ancora non ci posso credere!',cue:'exclamative'} ]
  }}
};
