// =====================================================================
//  BANQUE D'EXERCICES EN ALLEMAND (v6.19) — même structure que exercises-en.js
// =====================================================================
window.BANK_DE = {
  denomination:{ title:'Bilder benennen', items:{
    1:[ {emoji:'🐱',answer:'KATZE',choices:['KATZE','HUND','KANINCHEN']},
        {emoji:'🍎',answer:'APFEL',choices:['BIRNE','APFEL','PFLAUME']},
        {emoji:'🏠',answer:'HAUS',choices:['HAUS','AUTO','BAUM']},
        {emoji:'☀️',answer:'SONNE',choices:['SONNE','MOND','WOLKE']},
        {emoji:'🚗',answer:'AUTO',choices:['AUTO','FAHRRAD','BOOT']},
        {emoji:'🐟',answer:'FISCH',choices:['FISCH','VOGEL','PFERD']},
        {emoji:'🌹',answer:'BLUME',choices:['BLUME','GRAS','BLATT']},
        {emoji:'🍞',answer:'BROT',choices:['BROT','KUCHEN','KÄSE']} ],
    2:[ {emoji:'🦋',answer:'SCHMETTERLING',choices:['SCHMETTERLING','BIENE','LIBELLE']},
        {emoji:'⌚',answer:'UHR',choices:['UHR','BUCH','LAMPE']},
        {emoji:'🎻',answer:'GEIGE',choices:['GITARRE','GEIGE','CELLO']},
        {emoji:'🍄',answer:'PILZ',choices:['PILZ','TOMATE','ZWIEBEL']},
        {emoji:'🦒',answer:'GIRAFFE',choices:['GIRAFFE','KAMEL','ZEBRA']},
        {emoji:'⛵',answer:'SEGELBOOT',choices:['SEGELBOOT','SCHIFF','KANU']},
        {emoji:'🎺',answer:'TROMPETE',choices:['TROMPETE','FLÖTE','SAXOFON']},
        {emoji:'🌋',answer:'VULKAN',choices:['VULKAN','BERG','HÜGEL']} ],
    3:[ {emoji:'🧭',answer:'KOMPASS',choices:['KOMPASS','BAROMETER','THERMOMETER']},
        {emoji:'🦔',answer:'IGEL',choices:['IGEL','STACHELSCHWEIN','MAULWURF']},
        {emoji:'⚓',answer:'ANKER',choices:['ANKER','PROPELLER','RUDER']},
        {emoji:'🔬',answer:'MIKROSKOP',choices:['MIKROSKOP','TELESKOP','STETHOSKOP']},
        {emoji:'🪕',answer:'BANJO',choices:['BANJO','MANDOLINE','UKULELE']},
        {emoji:'🦦',answer:'OTTER',choices:['OTTER','WIESEL','MARDER']},
        {emoji:'🌪️',answer:'TORNADO',choices:['TORNADO','HURRIKAN','TAIFUN']},
        {emoji:'🛡️',answer:'SCHILD',choices:['SCHILD','RÜSTUNG','HELM']} ]
  }},
  completion:{ title:'Satz vervollständigen', items:{
    1:[ {text:'Die Katze trinkt ___',answer:'MILCH',choices:['MILCH','BROT','WASSER']},
        {text:'Ich schlafe in meinem ___',answer:'BETT',choices:['BETT','TELLER','SACK']},
        {text:'Die Sonne ist ___',answer:'GELB',choices:['GELB','KALT','SCHWER']},
        {text:'Ich esse mit einer ___',answer:'GABEL',choices:['GABEL','STUHL','TÜR']},
        {text:'Nachts ist der Himmel ___',answer:'SCHWARZ',choices:['SCHWARZ','GRÜN','RUND']},
        {text:'Ich gehe mit meinen ___',answer:'FÜSSEN',choices:['FÜSSEN','HÄNDEN','AUGEN']},
        {text:'Wir trinken aus einem ___',answer:'GLAS',choices:['GLAS','BUCH','MAUER']},
        {text:'Das Baby weint in der ___',answer:'WIEGE',choices:['WIEGE','GARTEN','OFEN']} ],
    2:[ {text:'Zum Schreiben benutze ich einen ___',answer:'STIFT',choices:['STIFT','HAMMER','BESEN']},
        {text:'Im Winter ist es sehr ___',answer:'KALT',choices:['HEISS','KALT','FEUCHT']},
        {text:'Der Briefträger bringt die ___',answer:'POST',choices:['POST','BROT','ZEITUNG']},
        {text:'Um die Tür zu öffnen, braucht man einen ___',answer:'SCHLÜSSEL',choices:['SCHLÜSSEL','LAMPE','TASSE']},
        {text:'Ich schaue einen Film im ___',answer:'FERNSEHEN',choices:['FERNSEHEN','RADIO','FENSTER']},
        {text:'Der Vogel baut sein ___',answer:'NEST',choices:['NEST','LOCH','MAUER']},
        {text:'Wir kaufen Brot in der ___',answer:'BÄCKEREI',choices:['BÄCKEREI','APOTHEKE','BANK']},
        {text:'Vor dem Essen wasche ich mir die ___',answer:'HÄNDE',choices:['HÄNDE','HAARE','ZÄHNE']} ],
    3:[ {text:'Vor dem Verlassen nicht vergessen, die Tür zu ___',answer:'SCHLIESSEN',choices:['SCHLIESSEN','ÖFFNEN','STREICHEN']},
        {text:'Der Arzt hat eine ___ verschrieben',answer:'BEHANDLUNG',choices:['BEHANDLUNG','NACHSPEISE','BLUMENSTRAUSS']},
        {text:'Das Treffen wurde auf morgen ___',answer:'VERSCHOBEN',choices:['VERSCHOBEN','GEGESSEN','GEMALT']},
        {text:'Du musst deine Steuern vor der Frist ___',answer:'ERKLÄREN',choices:['ERKLÄREN','TANZEN','GIESSEN']},
        {text:'Der Gärtner wird die Rosenbüsche ___',answer:'STUTZEN',choices:['STUTZEN','LESEN','SCHWIMMEN']},
        {text:'Nach dem Sport muss man sich ___',answer:'AUSRUHEN',choices:['AUSRUHEN','RENNEN','ÄRGERN']},
        {text:'Diese Geschichte ist schwer zu ___',answer:'GLAUBEN',choices:['GLAUBEN','NÄHEN','SCHNEIDEN']},
        {text:'Der Zeuge weigerte sich, ___',answer:'AUSZUSAGEN',choices:['AUSZUSAGEN','ANZURUFEN','ZU REISEN']} ]
  }},
  comprehension:{ title:'Anweisung verstehen', items:{
    1:[ {text:'Welches Tier bellt?',answer:'DER HUND',choices:['DER HUND','DER FISCH','DER VOGEL']},
        {text:'Womit isst man Suppe?',answer:'MIT EINEM LÖFFEL',choices:['MIT EINEM LÖFFEL','MIT EINEM MESSER','MIT EINER GABEL']},
        {text:'Wo schläft man?',answer:'IN EINEM BETT',choices:['IN EINEM BETT','IN EINER SCHÜSSEL','IN EINER TASCHE']},
        {text:'Welche Farbe hat Gras?',answer:'GRÜN',choices:['GRÜN','ROT','BLAU']},
        {text:'Was trinkt man bei Durst?',answer:'WASSER',choices:['WASSER','SAND','PAPIER']},
        {text:'Welches Objekt leuchtet nachts?',answer:'EINE LAMPE',choices:['EINE LAMPE','EIN KISSEN','EIN TELLER']} ],
    2:[ {text:'Welches Objekt zeigt die Uhrzeit an?',answer:'EINE UHR',choices:['EINE UHR','EIN BUCH','EINE LAMPE']},
        {text:'Welche Jahreszeit kommt nach dem Winter?',answer:'DER FRÜHLING',choices:['DER SOMMER','DER FRÜHLING','DER HERBST']},
        {text:'Wofür benutzt man einen Regenschirm?',answer:'UM TROCKEN ZU BLEIBEN',choices:['UM TROCKEN ZU BLEIBEN','ZUM ESSEN','ZUM SCHLAFEN']},
        {text:'Welcher Beruf behandelt Kranke?',answer:'DER ARZT',choices:['DER ARZT','DER BÄCKER','DER MALER']},
        {text:'Wie viele Tage hat eine Woche?',answer:'SIEBEN',choices:['SIEBEN','FÜNF','ZEHN']},
        {text:'Wo kauft man Medikamente?',answer:'IN DER APOTHEKE',choices:['IN DER APOTHEKE','BEI DER POST','IN DER WERKSTATT']} ],
    3:[ {text:'Wenn alle Rosen Blumen sind, ist eine Rose eine Blume?',answer:'JA',choices:['JA','NEIN','MANCHMAL','MAN WEISS ES NICHT']},
        {text:'Das Gegenteil von "schnell" ist:',answer:'LANGSAM',choices:['LANGSAM','LAUT','FRÖHLICH']},
        {text:'"Es regnet in Strömen" bedeutet:',answer:'ES REGNET STARK',choices:['ES REGNET STARK','ES IST SONNIG','ES IST WINDIG']},
        {text:'Peter ist größer als Paul. Wer ist kleiner?',answer:'PAUL',choices:['PAUL','PETER','BEIDE','KEINER']},
        {text:'"Eine neue Seite aufschlagen" bedeutet:',answer:'WEITERMACHEN',choices:['WEITERMACHEN','EIN BUCH LESEN','SICH AUSRUHEN']},
        {text:'Welches Wort ist kein Obst?',answer:'KAROTTE',choices:['KAROTTE','KIRSCHE','BANANE']} ]
  }},
  repetition:{ title:'Laut nachsprechen', voice:true, items:{
    1:[ {word:'BALL'},{word:'TISCH'},{word:'SONNE'},{word:'KATZE'},{word:'TÜR'},{word:'BLUME'},{word:'HAND'},{word:'WASSER'} ],
    2:[ {word:'COMPUTER'},{word:'REGENSCHIRM'},{word:'TELEFON'},{word:'BIBLIOTHEK'},{word:'RESTAURANT'},{word:'BERG'},{word:'GÄRTNER'},{word:'KALENDER'} ],
    3:[ {word:'HUBSCHRAUBER'},{word:'PHYSIOTHERAPEUT'},{word:'VERFASSUNGSWIDRIG'},{word:'PARALLELEPIPED'},{word:'HALS-NASEN-OHRENARZT'},{word:'CHRYSANTHEME'},{word:'DEMNÄCHST'},{word:'STATISTISCH'} ]
  }},
  denomination_orale:{ title:'Laut benennen', voice:true, items:{
    1:[ {emoji:'🐱',word:'KATZE'},{emoji:'🍎',word:'APFEL'},{emoji:'🏠',word:'HAUS'},{emoji:'☀️',word:'SONNE'},{emoji:'🚗',word:'AUTO'},{emoji:'🌹',word:'BLUME'} ],
    2:[ {emoji:'🦋',word:'SCHMETTERLING'},{emoji:'⌚',word:'UHR'},{emoji:'🍄',word:'PILZ'},{emoji:'🦒',word:'GIRAFFE'},{emoji:'⛵',word:'SEGELBOOT'},{emoji:'🎺',word:'TROMPETE'} ],
    3:[ {emoji:'🧭',word:'KOMPASS'},{emoji:'🦔',word:'IGEL'},{emoji:'⚓',word:'ANKER'},{emoji:'🔬',word:'MIKROSKOP'},{emoji:'🌪️',word:'TORNADO'},{emoji:'🛡️',word:'SCHILD'} ]
  }},
  fluence:{ title:'Wortflüssigkeit', voice:true, fluency:true, items:{
    1:[ {cat:'Tiere',accept:['katze','hund','kaninchen','pferd','kuh','huhn','schaf','schwein','vogel','fisch','maus','löwe','tiger','bär','wolf','fuchs','ente','esel','ziege','affe','elefant','giraffe','zebra','schlange','frosch']},
        {cat:'Obst',accept:['apfel','birne','banane','orange','erdbeere','kirsche','traube','kiwi','melone','pfirsich','aprikose','pflaume','zitrone','ananas','mango','himbeere','heidelbeere','wassermelone','feige','mandarine']} ],
    2:[ {cat:'Küchengegenstände',accept:['messer','gabel','löffel','teller','glas','topf','pfanne','ofen','kühlschrank','spüle','tisch','tasse','schüssel','sieb','spatel','schöpfkelle','platte','wasserkocher','teekanne']},
        {cat:'Kleidung',accept:['hose','hemd','pullover','kleid','rock','mantel','jacke','socke','schuh','schal','handschuh','mütze','shorts','t-shirt','krawatte','gürtel','stiefel','sandale','strumpfhose','strickjacke']} ],
    3:[ {cat:'Wörter, die mit dem Buchstaben B beginnen',accept:['ball','boot','brot','buch','boot','vogel','bett','flasche','banane','glocke','beutel','strand','bürste','knopf','bär','ast','brücke','korb','decke','butter']},
        {cat:'Berufe',accept:['arzt','bäcker','feuerwehrmann','lehrer','krankenschwester','anwalt','klempner','maler','koch','briefträger','gärtner','friseur','mechaniker','apotheker','elektriker','architekt','journalist','polizist','pilot','zahnarzt']} ]
  }},
  intonation:{ title:'Mit Betonung wiederholen', voice:true, items:{
    1:[ {word:'Bist du fertig?',cue:'question'},
        {word:'Bist du sicher?',cue:'question'},
        {word:'Ich komme morgen.',cue:'descriptive'},
        {word:'Du isst hier.',cue:'descriptive'},
        {word:'Komm her!',cue:'exclamative'},
        {word:'Was für eine gute Idee!',cue:'exclamative'} ],
    2:[ {word:'Was machst du gerade?',cue:'question'},
        {word:'Ach, wirklich?',cue:'question'},
        {word:'Sie spielt draußen.',cue:'descriptive'},
        {word:'Sie sprechen mit einem Freund.',cue:'descriptive'},
        {word:'Wie schön du bist!',cue:'exclamative'},
        {word:'Was für eine Überraschung!',cue:'exclamative'} ],
    3:[ {word:'Hast du letzte Nacht gut geschlafen?',cue:'question'},
        {word:'Könntest du mir helfen, das zu tragen?',cue:'question'},
        {word:'Wir werden morgen früh losfahren.',cue:'descriptive'},
        {word:'Der Briefträger kam, während du geschlafen hast.',cue:'descriptive'},
        {word:'Was für einen wunderbaren Tag wir hatten!',cue:'exclamative'},
        {word:'Ich kann es immer noch nicht glauben!',cue:'exclamative'} ]
  }}
};
