// =====================================================================
//  BANQUE D'EXERCICES EN ESPAGNOL (v6.19) — même structure que exercises-en.js
// =====================================================================
window.BANK_ES = {
  denomination:{ title:'Nombrar las imágenes', items:{
    1:[ {emoji:'🐱',answer:'GATO',choices:['GATO','PERRO','CONEJO']},
        {emoji:'🍎',answer:'MANZANA',choices:['PERA','MANZANA','CIRUELA']},
        {emoji:'🏠',answer:'CASA',choices:['CASA','COCHE','ÁRBOL']},
        {emoji:'☀️',answer:'SOL',choices:['SOL','LUNA','NUBE']},
        {emoji:'🚗',answer:'COCHE',choices:['COCHE','BICI','BARCO']},
        {emoji:'🐟',answer:'PEZ',choices:['PEZ','PÁJARO','CABALLO']},
        {emoji:'🌹',answer:'FLOR',choices:['FLOR','HIERBA','HOJA']},
        {emoji:'🍞',answer:'PAN',choices:['PAN','PASTEL','QUESO']} ],
    2:[ {emoji:'🦋',answer:'MARIPOSA',choices:['MARIPOSA','ABEJA','LIBÉLULA']},
        {emoji:'⌚',answer:'RELOJ',choices:['RELOJ','LIBRO','LÁMPARA']},
        {emoji:'🎻',answer:'VIOLÍN',choices:['GUITARRA','VIOLÍN','CHELO']},
        {emoji:'🍄',answer:'SETA',choices:['SETA','TOMATE','CEBOLLA']},
        {emoji:'🦒',answer:'JIRAFA',choices:['JIRAFA','CAMELLO','CEBRA']},
        {emoji:'⛵',answer:'VELERO',choices:['VELERO','CRUCERO','CANOA']},
        {emoji:'🎺',answer:'TROMPETA',choices:['TROMPETA','FLAUTA','SAXOFÓN']},
        {emoji:'🌋',answer:'VOLCÁN',choices:['VOLCÁN','MONTAÑA','COLINA']} ],
    3:[ {emoji:'🧭',answer:'BRÚJULA',choices:['BRÚJULA','BARÓMETRO','TERMÓMETRO']},
        {emoji:'🦔',answer:'ERIZO',choices:['ERIZO','PUERCOESPÍN','TOPO']},
        {emoji:'⚓',answer:'ANCLA',choices:['ANCLA','HÉLICE','TIMÓN']},
        {emoji:'🔬',answer:'MICROSCOPIO',choices:['MICROSCOPIO','TELESCOPIO','ESTETOSCOPIO']},
        {emoji:'🪕',answer:'BANJO',choices:['BANJO','MANDOLINA','UKELELE']},
        {emoji:'🦦',answer:'NUTRIA',choices:['NUTRIA','COMADREJA','MARTA']},
        {emoji:'🌪️',answer:'TORNADO',choices:['TORNADO','HURACÁN','TIFÓN']},
        {emoji:'🛡️',answer:'ESCUDO',choices:['ESCUDO','ARMADURA','CASCO']} ]
  }},
  completion:{ title:'Completar la frase', items:{
    1:[ {text:'El gato bebe ___',answer:'LECHE',choices:['LECHE','PAN','AGUA']},
        {text:'Duermo en mi ___',answer:'CAMA',choices:['CAMA','PLATO','BOLSA']},
        {text:'El sol es ___',answer:'AMARILLO',choices:['AMARILLO','FRÍO','PESADO']},
        {text:'Como con un ___',answer:'TENEDOR',choices:['TENEDOR','SILLA','PUERTA']},
        {text:'De noche, el cielo es ___',answer:'NEGRO',choices:['NEGRO','VERDE','REDONDO']},
        {text:'Camino con mis ___',answer:'PIES',choices:['PIES','MANOS','OJOS']},
        {text:'Bebemos de un ___',answer:'VASO',choices:['VASO','LIBRO','MURO']},
        {text:'El bebé llora en la ___',answer:'CUNA',choices:['CUNA','JARDÍN','HORNO']} ],
    2:[ {text:'Para escribir, uso un ___',answer:'BOLÍGRAFO',choices:['BOLÍGRAFO','MARTILLO','ESCOBA']},
        {text:'En invierno, hace mucho ___',answer:'FRÍO',choices:['CALOR','FRÍO','HÚMEDO']},
        {text:'El cartero trae el ___',answer:'CORREO',choices:['CORREO','PAN','PERIÓDICO']},
        {text:'Para abrir la puerta, necesito una ___',answer:'LLAVE',choices:['LLAVE','LÁMPARA','TAZA']},
        {text:'Veo una película en la ___',answer:'TELEVISIÓN',choices:['TELEVISIÓN','RADIO','VENTANA']},
        {text:'El pájaro construye su ___',answer:'NIDO',choices:['NIDO','AGUJERO','MURO']},
        {text:'Compramos pan en la ___',answer:'PANADERÍA',choices:['PANADERÍA','FARMACIA','BANCO']},
        {text:'Antes de comer, me lavo las ___',answer:'MANOS',choices:['MANOS','PELO','DIENTES']} ],
    3:[ {text:'Antes de salir, no olvides ___ la puerta',answer:'CERRAR',choices:['CERRAR','ABRIR','PINTAR']},
        {text:'El médico recetó un ___',answer:'TRATAMIENTO',choices:['TRATAMIENTO','POSTRE','RAMO']},
        {text:'La reunión fue ___ hasta mañana',answer:'APLAZADA',choices:['APLAZADA','COMIDA','PINTADA']},
        {text:'Debes ___ tus impuestos antes del plazo',answer:'DECLARAR',choices:['DECLARAR','BAILAR','REGAR']},
        {text:'El jardinero va a ___ los rosales',answer:'PODAR',choices:['PODAR','LEER','NADAR']},
        {text:'Después de hacer ejercicio, hay que ___',answer:'DESCANSAR',choices:['DESCANSAR','CORRER','ENFADARSE']},
        {text:'Esta historia es difícil de ___',answer:'CREER',choices:['CREER','COSER','CORTAR']},
        {text:'El testigo se negó a ___',answer:'TESTIFICAR',choices:['TESTIFICAR','LLAMAR','VIAJAR']} ]
  }},
  comprehension:{ title:'Entender la consigna', items:{
    1:[ {text:'¿Qué animal ladra?',answer:'EL PERRO',choices:['EL PERRO','EL PEZ','EL PÁJARO']},
        {text:'¿Con qué se come la sopa?',answer:'UNA CUCHARA',choices:['UNA CUCHARA','UN CUCHILLO','UN TENEDOR']},
        {text:'¿Dónde se duerme?',answer:'EN UNA CAMA',choices:['EN UNA CAMA','EN UN CUENCO','EN UNA BOLSA']},
        {text:'¿De qué color es la hierba?',answer:'VERDE',choices:['VERDE','ROJA','AZUL']},
        {text:'¿Qué se bebe cuando se tiene sed?',answer:'AGUA',choices:['AGUA','ARENA','PAPEL']},
        {text:'¿Qué objeto ilumina la noche?',answer:'UNA LÁMPARA',choices:['UNA LÁMPARA','UN COJÍN','UN PLATO']} ],
    2:[ {text:'¿Qué objeto indica la hora?',answer:'UN RELOJ',choices:['UN RELOJ','UN LIBRO','UNA LÁMPARA']},
        {text:'¿Qué estación viene después del invierno?',answer:'LA PRIMAVERA',choices:['EL VERANO','LA PRIMAVERA','EL OTOÑO']},
        {text:'¿Para qué sirve un paraguas?',answer:'PARA NO MOJARSE',choices:['PARA NO MOJARSE','PARA COMER','PARA DORMIR']},
        {text:'¿Qué profesión cuida a los enfermos?',answer:'EL MÉDICO',choices:['EL MÉDICO','EL PANADERO','EL PINTOR']},
        {text:'¿Cuántos días tiene una semana?',answer:'SIETE',choices:['SIETE','CINCO','DIEZ']},
        {text:'¿Dónde se compran medicamentos?',answer:'EN LA FARMACIA',choices:['EN LA FARMACIA','EN CORREOS','EN EL TALLER']} ],
    3:[ {text:'Si todas las rosas son flores, ¿es una rosa una flor?',answer:'SÍ',choices:['SÍ','NO','A VECES','NO SE SABE']},
        {text:'Lo contrario de "rápidamente" es:',answer:'LENTAMENTE',choices:['LENTAMENTE','FUERTEMENTE','ALEGREMENTE']},
        {text:'"Llueve a cántaros" significa:',answer:'LLUEVE MUCHO',choices:['LLUEVE MUCHO','HACE SOL','HACE VIENTO']},
        {text:'Pedro es más alto que Pablo. ¿Quién es más bajo?',answer:'PABLO',choices:['PABLO','PEDRO','LOS DOS','NINGUNO']},
        {text:'"Pasar página" significa:',answer:'SEGUIR ADELANTE',choices:['SEGUIR ADELANTE','LEER UN LIBRO','DESCANSAR']},
        {text:'¿Qué palabra no es una fruta?',answer:'ZANAHORIA',choices:['ZANAHORIA','CEREZA','PLÁTANO']} ]
  }},
  repetition:{ title:'Repetir en voz alta', voice:true, items:{
    1:[ {word:'PELOTA'},{word:'MESA'},{word:'SOL'},{word:'GATO'},{word:'PUERTA'},{word:'FLOR'},{word:'MANO'},{word:'AGUA'} ],
    2:[ {word:'ORDENADOR'},{word:'PARAGUAS'},{word:'TELÉFONO'},{word:'BIBLIOTECA'},{word:'RESTAURANTE'},{word:'MONTAÑA'},{word:'JARDINERO'},{word:'CALENDARIO'} ],
    3:[ {word:'HELICÓPTERO'},{word:'FISIOTERAPEUTA'},{word:'INCONSTITUCIONAL'},{word:'PARALELEPÍPEDO'},{word:'OTORRINOLARINGÓLOGO'},{word:'CRISANTEMO'},{word:'PRÓXIMAMENTE'},{word:'ESTADÍSTICAMENTE'} ]
  }},
  denomination_orale:{ title:'Nombrar en voz alta', voice:true, items:{
    1:[ {emoji:'🐱',word:'GATO'},{emoji:'🍎',word:'MANZANA'},{emoji:'🏠',word:'CASA'},{emoji:'☀️',word:'SOL'},{emoji:'🚗',word:'COCHE'},{emoji:'🌹',word:'FLOR'} ],
    2:[ {emoji:'🦋',word:'MARIPOSA'},{emoji:'⌚',word:'RELOJ'},{emoji:'🍄',word:'SETA'},{emoji:'🦒',word:'JIRAFA'},{emoji:'⛵',word:'VELERO'},{emoji:'🎺',word:'TROMPETA'} ],
    3:[ {emoji:'🧭',word:'BRÚJULA'},{emoji:'🦔',word:'ERIZO'},{emoji:'⚓',word:'ANCLA'},{emoji:'🔬',word:'MICROSCOPIO'},{emoji:'🌪️',word:'TORNADO'},{emoji:'🛡️',word:'ESCUDO'} ]
  }},
  fluence:{ title:'Fluidez verbal', voice:true, fluency:true, items:{
    1:[ {cat:'animales',accept:['gato','perro','conejo','caballo','vaca','gallina','oveja','cerdo','pájaro','pez','ratón','león','tigre','oso','lobo','zorro','pato','burro','cabra','mono','elefante','jirafa','cebra','serpiente','rana']},
        {cat:'frutas',accept:['manzana','pera','plátano','naranja','fresa','cereza','uva','kiwi','melón','melocotón','albaricoque','ciruela','limón','piña','mango','frambuesa','arándano','sandía','higo','mandarina']} ],
    2:[ {cat:'objetos de cocina',accept:['cuchillo','tenedor','cuchara','plato','vaso','olla','sartén','horno','nevera','fregadero','mesa','taza','cuenco','colador','espátula','cucharón','fuente','hervidor','tetera']},
        {cat:'ropa',accept:['pantalón','camisa','jersey','vestido','falda','abrigo','chaqueta','calcetín','zapato','bufanda','guante','gorro','pantalón corto','camiseta','corbata','cinturón','bota','sandalia','medias','rebeca']} ],
    3:[ {cat:'palabras que empiezan por B',accept:['barco','bola','pan','libro','bota','pájaro','cama','botella','plátano','campana','bolsa','playa','cepillo','botón','oso','rama','puente','cesta','manta','mantequilla']},
        {cat:'profesiones',accept:['médico','panadero','bombero','profesor','enfermera','abogado','fontanero','pintor','cocinero','cartero','jardinero','peluquero','mecánico','farmacéutico','electricista','arquitecto','periodista','policía','piloto','dentista']} ]
  }},
  intonation:{ title:'Repetir con entonación', voice:true, items:{
    1:[ {word:'¿Has terminado?',cue:'question'},
        {word:'¿Estás segur·o?',cue:'question'},
        {word:'Vengo mañana.',cue:'descriptive'},
        {word:'Comes aquí.',cue:'descriptive'},
        {word:'¡Ven aquí!',cue:'exclamative'},
        {word:'¡Qué buena idea!',cue:'exclamative'} ],
    2:[ {word:'¿Qué estás haciendo?',cue:'question'},
        {word:'¿Ah, sí?',cue:'question'},
        {word:'Ella juega afuera.',cue:'descriptive'},
        {word:'Hablan con un amigo.',cue:'descriptive'},
        {word:'¡Qué guapo/a estás!',cue:'exclamative'},
        {word:'¡Qué sorpresa!',cue:'exclamative'} ],
    3:[ {word:'¿Dormiste bien anoche?',cue:'question'},
        {word:'¿Podrías ayudarme a llevar esto?',cue:'question'},
        {word:'Saldremos temprano mañana.',cue:'descriptive'},
        {word:'El cartero vino mientras dormías.',cue:'descriptive'},
        {word:'¡Qué día tan maravilloso hemos tenido!',cue:'exclamative'},
        {word:'¡Todavía no me lo puedo creer!',cue:'exclamative'} ]
  }}
};
